package eventinfrastructure

type Event struct {
	Hostname         string    `json:"hostname,omitempty"`
	Timestamp        string    `json:"timestamp,omitempty"`
	LocalEnvironment bool      `json:"localEnvironment,omitempty"`
	Event            EventInfo `json:"event,omitempty"`
	Building         string    `json:"building,omitempty"`
	Room             string    `json:"room,omitempty"`
}

//event info contains information about the event itself.
type EventInfo struct {
	Type           EventType  `json:"type"`
	EventCause     EventCause `json:"eventCause"`
	Device         string     `json:"device"`
	EventInfoKey   string     `json:"eventInfoKey"`
	EventInfoValue string     `json:"eventInfoValue"`
}

//EVENT TYPES
type EventType uint16

const (
	ERROR EventType = iota
	DETAILSTATE
	CORESTATE
	USERACTION
	INFO
	HEARTBEAT
	HEALTH
)

func (e EventType) String() string {
	switch e {
	case ERROR:
		return "ERROR"
	case DETAILSTATE:
		return "DETAILSTATE"
	case CORESTATE:
		return "CORESTATE"
	case USERACTION:
		return "USERACTION"
	case INFO:
		return "INFO"
	case HEARTBEAT:
		return "HEARTBEAT"
	case HEALTH:
		return "HEALTH"

	}
	return ""
}

//EVENT CAUSE
type EventCause uint16

const (
	USERINPUT EventCause = iota
	AUTOGENERATED
	AWS
	INTERNAL
	STARTUP
)

func (e EventCause) String() string {
	switch e {
	case USERINPUT:
		return "USERINPUT"
	case AUTOGENERATED:
		return "AUTOGENERATED"
	case AWS:
		return "AWS"
	case INTERNAL:
		return "INTERNAL"
	case STARTUP:
		return "STARTUP"
	}
	return ""
}
