FROM resin/armv7hf-debian-qemu

RUN [ "cross-build-start" ]
# gcc for cgo
RUN apt-get update && apt-get install -y --no-install-recommends \
        g++ \
        gcc \
        libc6-dev \
        make \
        pkg-config \
        curl \ 
        git \
        libzmq3-dev \
    && rm -rf /var/lib/apt/lists/*

ENV GOLANG_VERSION 1.8.1
ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-armv6l.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 e8a8326913640409028ef95c2107773f989b1b2a6e11ceb463c77c42887381da

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
    && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
    && tar -C /usr/local -xzf golang.tar.gz \
    && rm golang.tar.gz

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH

RUN mkdir -p $GOPATH/src/github.com/byuoitav/zeromq-proxy-microservice
ADD . $GOPATH/src/github.com/byuoitav/zeromq-proxy-microservice

WORKDIR $GOPATH/src/github.com/byuoitav/zeromq-proxy-microservice
RUN go get -d -v
RUN go install -v

EXPOSE 7000

RUN [ "cross-build-end" ]
