FROM resin/raspberry-pi-alpine-golang

RUN apk update && apk add git
RUN apk add zeromq-dev && apk add build-base

RUN mkdir -p $GOPATH/src/github.com/byuoitav/zeromq-proxy-microservice
ADD . $GOPATH/src/github.com/byuoitav/zeromq-proxy-microservice

WORKDIR $GOPATH/src/github.com/byuoitav/zeromq-proxy-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/zeromq-proxy-microservice"]

EXPOSE 7000
