FROM golang:alpine

RUN apk update && apk add git
RUN apk add zeromq-dev && apk add build-base

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/zeromq-proxy-microservice

WORKDIR /go/src/github.com/byuoitav/zeromq-proxy-microservice
RUN go get -d -v
RUN go install -v

CMD ["/go/bin/zeromq-proxy-microservice"]

EXPOSE 7000
