FROM golang:alpine

ARG GITHUB_BRANCH

RUN apk update && apk add git

RUN mkdir -p /go/src/github.com/byuoitav
ADD . /go/src/github.com/byuoitav/event-router-microservice

WORKDIR /go/src/github.com/byuoitav/event-router-microservice

RUN go get -u github.com/FiloSottile/gvt

RUN gvt fetch -branch ${GITHUB_BRANCH} github.com/byuoitav/av-api

RUN go get -d -v
RUN go install -v

CMD ["/go/bin/event-router-microservice"]

EXPOSE 8004
